var students = [
    {
        "Pet_species": "Dog",
        "Pet_name" : "Clifford",
        "Pet_age" : "3",
        "Pet_gender" : male,
        "Pet_breed": beagle,
    
    }, 
    {
        "Pet_species": "Cat",
        "Pet_name" : "Khloe",
        "Pet_age" : "6",
        "Pet_gender" : female,
        "Pet_breed": tabby cat,   
    },
    {
       "Pet_species": "fish",
        "Pet_name" : "Joe",
        "Pet_age" : "50",
        "Pet_gender" : boy,
        "Pet_breed": gold fish,    
    },
    {
       "Pet_species": "Shark",
        "Pet_name" : "Bruce",
        "Pet_age" : "25",
        "Pet_gender" : boy,
        "Pet_breed": great white,      
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "Lola",
        "Pet_age" : "2",
        "Pet_gender" : girl,
        "Pet_breed": husky,      
    },
    {
        "Pet_species": "Crab",
        "Pet_name" : "Sebastian",
        "Pet_age" : "5",
        "Pet_gender" : boy,
        "Pet_breed": alaskan snow crab,    
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "Lassie",
        "Pet_age" : "18",
        "Pet_gender" : girl,
        "Pet_breed": Rough Collie,  
    },
    {
        "Pet_species": "Cat",
        "Pet_name" : "Garfield",
        "Pet_age" : "3",
        "Pet_gender" : boy,
        "Pet_breed": exotic short hair,
    {
        "Pet_species": "Dog",
        "Pet_name" : "George",
        "Pet_age" : "5",
        "Pet_gender" : boy,
        "Pet_breed": german shepard,      
    },
    {
       "Pet_species": "cat",
        "Pet_name" : "spot",
        "Pet_age" : "4",
        "Pet_gender" : boy,
        "Pet_breed": persian,
    {
        "Pet_species": "Mulan",
        "Pet_name" : "fish",
        "Pet_age" : "10",
        "Pet_gender" : girl,
        "Pet_breed":      
    },
    {
        "Pet_species": "fish",
        "Pet_name" : "goldy",
        "Pet_age" : "1",
        "Pet_gender" : girl,
        "Pet_breed": gold fish,
    {
       "Pet_species": "fish",
        "Pet_name" : "dory",
        "Pet_age" : "7",
        "Pet_gender" : boy,
        "Pet_breed": blue tang fish,       
    },
    {
       "Pet_species": "fish",
        "Pet_name" : "nemo",
        "Pet_age" : "5",
        "Pet_gender" : boy,
        "Pet_breed": clown fish,      
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "charlie",
        "Pet_age" : "4",
        "Pet_gender" : boy,
        "Pet_breed": labrador,      
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "cooper",
        "Pet_age" : "8",
        "Pet_gender" : boy,
        "Pet_breed": chihuahua,     
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "Toto",
        "Pet_age" : "7",
        "Pet_gender" : boy,
        "Pet_breed": cairn terrier,     
    },
    {
        "Pet_species": "cat",
        "Pet_name" : "rose",
        "Pet_age" : "3",
        "Pet_gender" : girl,
        "Pet_breed": british shorthair,       
    },
    {
       "Pet_species": "cat",
        "Pet_name" : "fluffy",
        "Pet_age" : "10",
        "Pet_gender" : boy,
        "Pet_breed": tabby cat,    
    },
    {
        "Pet_species": "Dog",
        "Pet_name" : "sparky",
        "Pet_age" : "3",
        "Pet_gender" : boy,
        "Pet_breed": golden retriever,     
    }
     
];